MQTT_CONNECT = 0x01
MQTT_CONNACK = 0x02

SIGNATURE_CLIENT_HELLO = 0xA1
SIGNATURE_SERVER_HELLO = 0xA2
SIGNATURE_CLIENT_KEM_CIPHERTEXT = 0xA3
SIGNATURE_CLIENT_FINISHED = 0xA4
SIGNATURE_SERVER_FINISHED = 0xA5
